services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    restart: always
    # ports:
    #   - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20

  auth:
    build: ./auth-service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  game-mail:
    build: ./game-mail-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data:
  redis_data:
