services:
  db:
    image: postgres:15-alpine
    restart: always

    environment:
      POSTGRES_USER_FILE: /run/secrets/DB_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/DB_NAME

    secrets:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$(cat /run/secrets/DB_USER)\" -d \"$(cat /run/secrets/DB_NAME)\""]
      interval: 3s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 20

  auth:
    build: ./auth-service
    restart: always
    ports:
      - "3000:3000"
    secrets:
      - ACCESS_SECRET
      - REFRESH_SECRET
      - ADMIN_SECRET_KEY
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  game-mail:
    build: ./game-mail-service
    restart: always
    ports:
      - "3001:3001"
    secrets:
      - ACCESS_SECRET
      - ADMIN_SECRET_KEY
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - FIREBASE_SERVICE_ACCOUNT_JSON
    environment:
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: debug
      SSE_DEBUG: "1"
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

secrets:
  ACCESS_SECRET:
    file: ./secrets/ACCESS_SECRET
  REFRESH_SECRET:
    file: ./secrets/REFRESH_SECRET
  ADMIN_SECRET_KEY:
    file: ./secrets/ADMIN_SECRET_KEY
  DB_USER:
    file: ./secrets/DB_USER
  DB_PASSWORD:
    file: ./secrets/DB_PASSWORD
  DB_NAME:
    file: ./secrets/DB_NAME
  FIREBASE_SERVICE_ACCOUNT_JSON:
    file: ./secrets/FIREBASE_SERVICE_ACCOUNT_JSON

volumes:
  db_data:
  redis_data:
